#!/usr/bin/python3
from requests import get
import json
from random import choice
from myutil import mail
import sys

# TODO: Change Variables for sending the mail:
sender = "whaterver@domain.com"
mailserver = "yourmailserver.com"
port = 25
# Only needed if your mailserver need user authentication
mail_password = "your secure mail password"
subject = "Your mail subject"
receipient = "Your mail receipient"

# OR use default vars in $HOME/.local/lib/python3.6/site-packages/myutil_defaults.py
# and just specify this
subject = "Your mail subject"
receipient = "Your mail receipient"

'''API's:
    Jokes:
    https://sv443.net/jokeapi/category/Any
    https://icanhazdadjoke.com
    https://fortuneapi.herokuapp.com
    https://geek-jokes.sameerkumar.website/api

    Quotes:
    https://corporatebs-generator.sameerkumar.website
    https://ron-swanson-quotes.herokuapp.com/v2/quotes
    https://api.tronalddump.io/random/quote
'''

def sv443(category=None):
    if category == None:
        category = "Any"
    else:
        category = category

    joke = get('https://sv443.net/jokeapi/category/'+category)
    if joke.status_code == 200:
        category = json.loads(joke.text)["category"]
        type = json.loads(joke.text)["type"]
        if type == "single":
            answer = json.loads(joke.text)["joke"]
        elif type == "twopart":
            answer = json.loads(joke.text)["setup"]
            answer = answer + " - " + json.loads(joke.text)["delivery"]
        return answer + " - SV443"
    else:
        sv443(category)

def sv443_computers():
    return sv443("Programming") + " - Programming"


def icanhazdad():
    headers = {'Accept': 'text/plain'}
    joke = get('https://icanhazdadjoke.com/', headers=headers)
    if joke.status_code == 200:
        # Fix some broken characters
        joke = joke.text
        joke = joke.replace("â\x80\x93", "-")
        joke = joke.replace("â\x80\x99", "'")
        joke = joke.replace("â", "\"")
        joke = joke.replace("â", "\"")
        joke = joke.replace("â¦", "...")
        return joke + " - Dad Jokes"
    else:
        icanhazdad()

def fortune():
    headers = {'Accept': 'text/plain'}
    joke = get('https://fortuneapi.herokuapp.com')
    if joke.status_code == 200:
        if joke.text.endswith("\n"):
            joke = joke.text[1:-2]
        else:
            joke = joke.text
        if joke.startswith("\""):
            joke = joke[1:]
        if joke.endswith("\""):
            joke = joke[:-1]
        joke = joke.replace("\\n", "\n")
        joke = joke.replace("\\t", "\t")
        joke = joke.replace("\\r", "\r")
        joke = joke.replace('\\"', "\"")
        return joke.strip()  + " - Fortune"
    else:
        fortune()

def geek():
    joke = get('https://geek-jokes.sameerkumar.website/api')
    if joke.status_code == 200:
        return joke.text[1:-2] + " - Geek Jokes"
    else:
        geek()

def bs_generator():
    joke = get('https://corporatebs-generator.sameerkumar.website')
    if joke.status_code == 200:
        joke = json.loads(joke.text)["phrase"]
        return joke + " - Bullshit Generator"
    else:
        bs_generator()

def ronswanson():
    quota = get('https://ron-swanson-quotes.herokuapp.com/v2/quotes')
    if quota.status_code == 200:
        return quota.text[1:-1][1:-1] + " - Ron Swanson"
    else:
        ronswanson()

def trump():
    quota = get('https://api.tronalddump.io/random/quote')
    if quota.status_code == 200:
        return json.loads(quota.text)["value"] + " - Donald Trump"
    else:
        trump()

def random_choice():
    # Get a random joke and a random quote
    random_joke = choice([sv443, sv443_computers, icanhazdad, fortune, geek])()
    random_quote = choice([bs_generator, ronswanson, trump])()
    text = random_joke + "\n\n" + random_quote
    return text

text = random_choice()
# Depending on what you choosed redarding default vars above
# email = mail.setup(sender, mailserver, port, password=mail_password)
# OR this
email = mail.setup()
email.send(subject, text, receipient)
