#!/usr/bin/python3
#-*- coding: utf-8 -*-

import random
import string

def gen_password(password_length):
    allowed_characters = string.ascii_uppercase+string.ascii_lowercase+string.digits+"!#$%&()*+-,./:;<=>?@"   #+string.punctuation

    generated_password = "".join(random.choice(allowed_characters) for i in range(password_length))

    return generated_password

while True:
    input = input("Please enter desired length of password in full numbers: ")
    try:
        password_length = int(input)
        print(gen_password(password_length))
        break
    except:
        print("Please enter a full number!")
